version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
      # postgres container listens on 5432 by default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      # https://github.com/docker/compose/issues/1837
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=${DB_PORT}
        - DB_HOST=${DB_HOST}
        - DJANGO_KEY=${DJANGO_KEY}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data: